# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f7ea6943af87a4a99a36cba71f0db51b2a0b3db9bb374304f5653c8468a9c16ea9ac25ecdaa2ddb26443b5af6bf19a1c70dacae5fcafe9e12edcb18b42b9f5

test:
  secret_key_base: 456e7adc39f2b6094c8487e67e16192a61fe8fea6a6282d64ca62cd5e50349652b85054814f63074f318977eff1a40a6116c8a422bb342df268bec9dae2cac21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
